apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.33.100-192.168.33.109
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement-master
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: master
  interfaces:
  - enp0s8
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: second-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.33.110-192.168.33.119
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement-master
  namespace: metallb-system
spec:
  ipAddressPools:
  - second-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: node-1
  interfaces:
  - enp0s8
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: third-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.33.120-192.168.33.129
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement-master
  namespace: metallb-system
spec:
  ipAddressPools:
  - third-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: node-2
  interfaces:
  - enp0s8

