#!/bin/bash

create(){
  /sbin/modprobe dummy
  for (( c=$2 ; c<=$3 ; c++ )) ; do
    /sbin/ip addr add $1.$c/24 brd + dev $4 >/dev/null 2>&1
  done
}
remove(){
  for (( c=$2 ; c<=$3 ; c++ )) ; do
    /sbin/ip addr del $1.$c/24 brd + dev $4 >/dev/null 2>&1
  done
}
usage(){
  echo "Usage: $(basename $0) {create|remove} <baseIP> <StartRange> <StopRange> <Dev>"
  echo "Example: $(basename $0) create 192.168.33 100 109 enp0s8 "
}

rx='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
dev=$(/sbin/ip link show up | grep default | awk '{ print $2 }' | sed 's/.$//' | grep -x ^$5)
if [ $# -ne 5 ] ; then
  usage
  exit 1
elif [ -z $dev ] ; then
  usage
  exit 2
elif [[ ! $2 =~ ^$rx\.$rx\.$rx$ ]] ; then
  usage
  exit 3
elif [[ ! $3 =~ ^-?[0-9]+$ ]] || [[ ! $4 =~ ^-?[0-9]+$ ]] || [[  $3 -gt $4 ]] ; then
  usage
  exit 4
fi

case $1 in
  create)
      create $2 $3 $4 $5
      exit 0;;
  remove)
      remove $2 $3 $4 $5
      exit 0;;
  *)
    usage;;
esac