#!/bin/bash

create(){
  /sbin/modprobe dummy
  for (( c=$1 ; c<=$2 ; c++ )) ; do
    /sbin/ip addr add 192.168.33.$c/24 brd + dev $3 >/dev/null 2>&1
  done
}
remove(){
  for (( c=$1 ; c<=$2 ; c++ )) ; do
    /sbin/ip addr del 192.168.33.$c/24 brd + dev $3 >/dev/null 2>&1
  done
}
usage(){
  echo "Usage: $0 {create|remove} <StartRange> <StopRange> <Dev>"
}

dev=$(/sbin/ip link show up | grep default | awk '{ print $2 }' | sed 's/.$//' | grep -x ^$4)
if [ $# -ne 4 ] ; then
  usage
  exit 1
elif [ -z $dev ] ; then
  usage
  exit 3
elif [[ ! $2 =~ ^-?[0-9]+$ ]] || [[ ! $3 =~ ^-?[0-9]+$ ]] || [[  $2 -gt $3 ]] ; then
  usage
  exit 2
fi

case $1 in
  create)
      create $2 $3 $4
      exit 0;;
  remove)
      remove $2 $3 $4
      exit 0;;
  *)
    usage;;
esac